name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the solution
        run: dotnet build "CommunityFixes.sln" -c Release

      - name: Find zip
        id: find-zip
        run: |
          echo "zip=$(ls -1 dist/CommunityFixes-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name=CommunityFixesRelease" >> $GITHUB_ENV

      - name: Upload zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.zip }}
