name: Space Warp Version Checker

on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify KSP2 Mod
        uses: Rexicon226/VerifierAction@V0.5

      - name: KSP2 Builder
        uses: Rexicon226/KSP2Builder@V0.1